### ISSUE TITLE
Blank windrose when selecting 16+ hours of data

### ISSUE THREAD

**Issue by BrainStone** [aukedejong/lovelace-windrose-card#1]
Whenever I select to show 16 or more hours, I get a blank windrose and this error shows up in my browser console:

```
Uncaught (in promise) TypeError: firstSpeedData[i] is undefined
    updateWindData https://home-assistant.example.com/hacsfiles/lovelace-windrose-card/windrose-card.js?hacstag=591270696010:975
```

Line: `windrose-card.js:975:76`  
Version: 0.1.0 and 0.0.2 (did not try 0.0.1)

**Comment by BrainStone** [comment]
Interesting, now it breaks for values around 10.

I have this:
```
Historie 
Object { "sensor.aussen_windrichtung": (11) […], "sensor.aussen_windgeschwindigkeit": (10) […] }
​
"sensor.aussen_windgeschwindigkeit": Array(10) [ {…}, {…}, {…}, … ]
​​
0: Object { s: "10.4", a: {…}, lu: 1674631452.043 }
​​
1: Object { s: "11.9", a: {…}, lu: 1674633734.461797 }
​​
2: Object { s: "12.2", a: {…}, lu: 1674637334.555443 }
​​
3: Object { s: "14.0", a: {…}, lu: 1674640934.577477 }
​​
4: Object { s: "13.3", a: {…}, lu: 1674648134.58438 }
​​
5: Object { s: "13.0", a: {…}, lu: 1674651734.553474 }
​​
6: Object { s: "11.9", a: {…}, lu: 1674655334.58846 }
​​
7: Object { s: "10.8", a: {…}, lu: 1674658934.56704 }
​​
8: Object { s: "8.6", a: {…}, lu: 1674662534.500704 }
​​
9: Object { s: "7.9", a: {…}, lu: 1674666134.606221 }
​​
length: 10
​​
<prototype>: Array []
​
"sensor.aussen_windrichtung": Array(11) [ {…}, {…}, {…}, … ]
​​
0: Object { s: "42.0", a: {…}, lu: 1674631452.043 }
​​
1: Object { s: "45.7", a: {…}, lu: 1674633734.462018 }
​​
2: Object { s: "57.7", a: {…}, lu: 1674637334.555696 }
​​
3: Object { s: "56.7", a: {…}, lu: 1674640934.57772 }
​​
4: Object { s: "50.8", a: {…}, lu: 1674644534.535906 }
​​
5: Object { s: "48.2", a: {…}, lu: 1674648134.584629 }
​​
6: Object { s: "53.3", a: {…}, lu: 1674651734.55373 }
​​
7: Object { s: "54.4", a: {…}, lu: 1674655334.588726 }
​​
8: Object { s: "56.9", a: {…}, lu: 1674658934.567312 }
​​
9: Object { s: "46.8", a: {…}, lu: 1674662534.500953 }
​​
10: Object { s: "21.9", a: {…}, lu: 1674666134.606517 }
​​
length: 11
​​
<prototype>: Array []
​
<prototype>: Object { … }
```

This was for 10 hours.
I'm gathering the data from the built-in Forecast Home, though from what I can tell the timepoints the data is collected only varies by a few ms.

**Comment by aukedejong** [comment]
There are 10 wind speeds measurements and 11 direction measurements. That's the problem.
I just release a new version that checks for this and prints a message in the console.

Maybe I can work around this in the code, but have to think about it. It makes things more complex.

**Comment by BrainStone** [comment]
I think the clean solution would be to try to map the value pairs together by their timestamp

**Comment by aukedejong** [comment]
I agree. It make it more complex and cpu heavy.

My windmeter delivers data packages with both speed direction, so I always get the same number of measurements.

I'll think about this. This will not be a quick fix.

**Comment by BrainStone** [comment]
It's ok that it's not a quick fix.  
What's interesting to me is that it should be able to have lined up data. As you can see it's only a few ms off. This might be fixable through a different query.

**Comment by aukedejong** [comment]
Wind direction measurement 4 doesn't have a corresponding speed measurement.  The card would have to skip this measurement or use the previous speed measurement....

**Comment by aukedejong** [comment]
Released v0.2.0
This version should match direction measurements with speed measurement which are at most one second earlier or later.

**Comment by tomlut** [comment]
I'm getting a blank card now whereas prior to 0.2.0 it was working:
```
Uncaught (in promise) Error: The direction and speed entities should have the same number of measurements for a period.
    updateWindData https://96zke8stt3d3i25a3vbdumw0vrkeb2ie.ui.nabu.casa/hacsfiles/lovelace-windrose-card/windrose-card.js?hacstag=591270696011:974
```

**Comment by BrainStone** [comment]
It's working for me.

**Comment by aukedejong** [comment]
@tomlut Looks like your browser cache still has an older version.  I removed this specifiek error message in 0.2.0, it only exists in 0.1.1

I think it's time to add a version banner in the console.

**Comment by aukedejong** [comment]
It's fixed for BrainStone, so I'll close this issue.   @tomlut, please open a new issue if you can't get it to work.
