### ISSUE TITLE
[Feature request] Option to convert degrees to cardinal letters in corner info.

### ISSUE THREAD

**Issue by amrij** [aukedejong/lovelace-windrose-card#100]
![afbeelding](https://github.com/user-attachments/assets/88f704d3-f226-49dc-a883-a41a01702247)

**Comment by aukedejong** [comment]
Can you also share your complete card configuration, so I can copy paste it?

Thanks.

**Comment by amrij** [comment]
type: custom:windrose-card
title: Windrichting
corner_info:
  top_left:
    label: Windsnelheid
    unit: " km/h"
    entity: sensor.windsnelheid_dak
  top_right:
    label: Windvlaag
    unit: " km/h"
    entity: sensor.windvlaag_dak
  bottom_left:
    label: Windrichting
    unit: °
    entity: sensor.windrichting_dak
data_period:
  from_hour_of_day: 0
refresh_interval: 300
windspeed_bar_location: bottom
windspeed_bar_full: true
wind_direction_entity:
  entity: sensor.windrichting_dak
  use_statistics: false
  direction_compensation: 0
windspeed_entities:
  - entity: sensor.windsnelheid_dak
    name: Windsnelheid
    speed_unit: kph
    use_statistics: false
  - entity: sensor.windvlaag_dak
    name: Windvlaag
    speed_unit: kph
    use_statistics: false
output_speed_unit: kph
speed_range_beaufort: false
speed_range_step: 5
speed_range_max: 80
speed_ranges:
  - from_value: 0
    color: rgb(0,255,0)
  - from_value: 5
    color: yellow
  - from_value: 10
    color: hsl(200, 100%, 60%)
  - from_value: 15
    color: hsl(200, 100%, 60%)
  - from_value: 20
    color: orange
  - from_value: 25
    color: orange
  - from_value: 30
    color: orange
  - from_value: 35
    color: orange
  - from_value: 40
    color: cyan
  - from_value: 45
    color: cyan
  - from_value: 50
    color: cyan
  - from_value: 55
    color: cyan
  - from_value: 60
    color: red
  - from_value: 65
    color: red
  - from_value: 70
    color: red
  - from_value: 75
    color: red
windrose_draw_north_offset: 0
current_direction:
  show_arrow: true
  arrow_size: 50
  center_circle_size: 30
compass_direction:
  auto_rotate: false
  entity: sensor.windrichting_dak
cardinal_direction_letters: NOZW
wind_direction_count: 32
direction_letters: NOZWB
matching_strategy: time-frame
center_calm_percentage: true

**Comment by aukedejong** [comment]
In what way, not displaying all wind directions?
I count 8 leaves in a quadrant, that is 32 for all directions.
If you mean that some directions have no leave, then from these direction the wind hasn't blown hard enough.

Maybe turning off center_calm_speed?

**Comment by amrij** [comment]
The wind direction isn't shown in letters. For example: NNO.

**Comment by aukedejong** [comment]
Ah, this is a feature request.

Currently only 4 labels can be displayed.
You want them all displayed.

**Comment by aukedejong** [comment]
In your screencapture I see 200 as the current direction value. 
Corner info left bottom.

There you want to see the direction in letters?

Your entity uses degrees?
So you want a feature that translates degrees to cardinal letters?

**Comment by amrij** [comment]
Yes, I would like to

**Comment by aukedejong** [comment]
Nice, I will change the title of this issue.
It added to the list of request.

There is a work around available.
You can create a template sensor translation the degrees to cardinal letters.
Example here:
[https://community.home-assistant.io/t/convert-wind-direction-degrees-to-text/257379](https://community.home-assistant.io/t/convert-wind-direction-degrees-to-text/257379)

**Comment by aukedejong** [comment]
Feature added in version 1.12.0.
