### ISSUE TITLE
Error Message

### ISSUE THREAD

**Issue by wagnerpizza** [aukedejong/lovelace-windrose-card#101]
Hi,

this is my Script and it Shows some error with „Cardinal letters Not defined“

![IMG_0038](https://github.com/user-attachments/assets/199e4166-bb48-494a-8f61-90bbd8d14729)

**Comment by aukedejong** [comment]
The value of cardinal_direction_letters should be like this:

cardinal_direction_letters: NESW

Or

cardinal_direction_letters: North,East,South,West

So, 4 letters or 4 comma separated words.

Somebody else made the same mistake. I think I need to improve the readme.
Thanks.

**Comment by wagnerpizza** [comment]
Hi thanks for the fast reply.Could you send me the lower Part of the Script with Right Syntax?Because i add nwse and same errorVon meinem iPad gesendetAm 20.11.2024 um 21:42 schrieb Auke de Jong ***@***.***>:﻿
The value of cardinal_direction_letters should be like this:
cardinal_direction_letters: NESW
Or
cardinal_direction_letters: North,East,South,West
So, 4 letters or 4 comma separated words.
Somebody else made the same mistake. I think I need to improve the readme.
Thanks.

**Comment by aukedejong** [comment]
It's a bug in the initial config, when adding the card.

I'll fix this.
