### ISSUE TITLE
Doesn't handle a fixed Wind Direction

### ISSUE THREAD

**Issue by gedger** [aukedejong/lovelace-windrose-card#102]
I'm in the middle of storm Bert and the wind has been coming from a steady southerly direction for hours now. Unfortunately the windrose stops updating as I think the "no change" detection logic is seeing the none changing 180 degree direction and assuming something is wrong? If this is then case I think the detection logic needs to also consider the other entities as well and only not update when none of the entities has changed in the reporting period?

Edit: Have confirmed this is the case as I have swapped the wind_dir sensor which  hasn't changed with a wind_gust_direction sensor which has had a few transitions in the last 3 hours and the windrose card is now displaying .

**Comment by aukedejong** [comment]
I need to investigate this one.

The rose leaves should update on a time interval, config: refresh_interval, default every 5 minutes.
If the wind direction is constant, I think we need to change the matching strategy.

The time-frame option could fix this.
You can read me details about the in the readme.

**Comment by aukedejong** [comment]
I'm thinking about adding a new strategy that calculates the duration of every wind speed and direction combination in seconds.
It will make the logic more complex and maybe to hungry for CPU power.

**Comment by gedger** [comment]
I’ve changed the matching strategy to time frame and that has given a good result, I’ll monitor over the next day as the conditions change.

**Comment by gedger** [comment]
Been thinking about this and it's a hard one to have a matching strategy that works under all circumstances. 

Having a fixed wind direction with a variable speed is valid.
Having a fixed speed, typically zero during lulls or below the measuring capability of the anemometer but with a variable direction is valid
Having zero speed and none changing direction is valid too.

Needs a ponder....

**Comment by aukedejong** [comment]
Hi,
I added the full-time matching strategy.
For every speed measurement it determines the 'active' direction measurement. The same for every direction measurement.
Then it determines the amount of seconds that measurement combination was active. With that information the percentages are determined.

I think this would result in the most correct graph, only down side, it takes some more CPU power.
For my sensors, 200 hours history, there is not much difference between the matching strategy's.

What are your results?

**Comment by aukedejong** [comment]
I agree, this one can be closed.
If you see any faulty behaviour, let me know.
Thanks.
