### ISSUE TITLE
Feature request: yaml entry to change font-size of corner texts

### ISSUE THREAD

**Issue by MaxVonEvil** [aukedejong/lovelace-windrose-card#104]
While it's nice to be able to add additional entities to the corners around the windrose, I would like to see some controls for font-size as the current scaling makes the text a little too big, as seen here:

![image](https://github.com/user-attachments/assets/380288b6-3d10-4627-978d-6a70c834371a)

**Comment by reidprichard** [comment]
I agree that more font sizes would be useful. An easy solution could be just adding some descriptive classes to things so font size could be edited with card-mod. Right now all the text seems to just be 'text' elements with no classes, so you can't set different sizes per element (e.g. larger NESW but same size legend labels).

**Comment by aukedejong** [comment]
I'm working on some feature request. Hopefully I can release before Christmas.

**Comment by aukedejong** [comment]
Feature added in version 1.12.0.
Also added classes.
