### ISSUE TITLE
Unable to install into HA 2024.12.0

### ISSUE THREAD

**Issue by goberhammer** [aukedejong/lovelace-windrose-card#105]
Ok... maybe I'm missing something really simple/stupid... but I'm not able to install this extension with HACS on HA 2024.12.0

I cannot find with the HACS search bar, and if I try to add the repository it tells me that the repo is already installed ( "Repository 'aukedejong/lovelace-windrose-card' exists in the store" )

I don't see anyone mentioning installation problems, so I'm doing something wrong for sure... :-)

**Comment by aukedejong** [comment]
I did not update HA myself yet.
I'll try later today.

**Comment by aukedejong** [comment]
Finally found the time to update HA.  The card still works on my installation.
I've don't know how to help you with this.
Maybe someone on the HA forum can help you with this.

**Comment by goberhammer** [comment]
Thanks a lot for taking the time to look into this. Have a nice weekend.
