### ISSUE TITLE
Center_calm_percentage option is available in two places

### ISSUE THREAD

**Issue by il77781** [aukedejong/lovelace-windrose-card#110]
@aukedejong, hello!
As far as I can tell from the documentation provided, the `center_calm_percentage` option can now be specified in two places: both for the card itself and for each of the windspeed entities. To be honest, it's not entirely clear why this was done... After all, there is only one graph anyway, and it displays values only for the first of the windspeed entities... At the same time, if you remove `center_calm_percentage` from the settings of the card itself, then, as if, the options `center_calm_percentage` specified for windspeed entities do not work... 
Or do I just misunderstand how they work?

**Comment by aukedejong** [comment]
Fixed.
Documentation bug. I moved some options from main to windspeed entity level. Copy pasted one option to much.

Thanks.

**Comment by il77781** [comment]
Yes, that's what I thought, thanks!
