### ISSUE TITLE
Pointer Missing when action used on Speedbar 1 when showing on right

### ISSUE THREAD

**Issue by dcapslock** [aukedejong/lovelace-windrose-card#111]
Pointer Missing when action used on Speedbar 1 when showing on right. This scenarion missed when addressing #109 

https://github.com/aukedejong/lovelace-windrose-card/blob/f6f067737f775c11ed98928aa677cd90ccb26bb4/src/renderer/TouchFacesRenderer.ts#L66-L77

**Comment by aukedejong** [comment]
Thanks.
Fixed in version 1.12.3
