### ISSUE TITLE
v1.12.5 - Empty quotes to hide wind direction letters not working

### ISSUE THREAD

**Issue by jazzyisj** [aukedejong/lovelace-windrose-card#114]
Per the docs:

<img width="268" alt="image" src="https://github.com/user-attachments/assets/341d4781-17bb-4d61-bedf-5ae578c31731" />

`cardinal_direction_letters: " "` results in an error.

<img width="310" alt="image" src="https://github.com/user-attachments/assets/b38dcc08-010d-4ab9-b9c7-91e0c2b6c054" />

Edit:

`cardinal_direction_letters: " , , , "`  This works.

<img width="110" alt="image" src="https://github.com/user-attachments/assets/47b2c1eb-4a95-4fa4-af64-7d59503e0788" />

**Comment by aukedejong** [comment]
Hi,
Your config has a space in it, that's not an empty string. At least the windrose card doesn't think so.

cardinal_direction_letters: ''   works on the latest version.

Maybe it's better to remove leading and trailing spaces in the card.
What I did for now is clarifying the error message.

**Comment by jazzyisj** [comment]
Ah gotcha.  Guess I made an assumption based on other cards I use requiring a space to hide titles and whatnot.  

Perhaps a less ambiguous option such as "`none`" or "`false`" would solve any confusion, but the error here was definitely on my part!

Thanks for looking at it so quickly!  Great card!

**Comment by aukedejong** [comment]
Thanks, also for the suggestions on how to make it better.

**Comment by aukedejong** [comment]
Improved error message about cardinal_direction_letters config in version 1.12.6.
