### ISSUE TITLE
Display on top of picture card

### ISSUE THREAD

**Issue by sanderlv** [aukedejong/lovelace-windrose-card#12]
Hi, maybe not the right place to ask here. But since I really like the concept of this card but mainly use the picture elemnts card in hass I would like to know of it is possible to "transparant" display your card on top of my existing "garden" card. Would that be possible?

**Comment by aukedejong** [comment]
HI Sander.
I'm not sure I understand your question correctly.   You want to display a windrose on a picture elements card. Is that correct?
I don't have experience with the picture elements card. I see there is a custom option.

If you need a transparent background option in the windrose card, I think that possible.

**Comment by sanderlv** [comment]
Yes, correct. I can start investigating myself but hoped you would have a ready to use option 😀.

**Comment by aukedejong** [comment]
I'm sorry, I don't have a ready to use option.

So, to be sure, a transparent background options would make this possible, right?

I will have look at this, see how easy it can be done.

**Comment by sanderlv** [comment]
Transparent would indeed help a lot!

**Comment by aukedejong** [comment]
Hi Sander. I had a look at the code and decided not to make an option for this in de card itself.

You can change the background color of the card with card_mod.
See: https://github.com/thomasloven/lovelace-card-mod

If you add this to the card configuration:
`card_mod:
  style: |
    ha-card {
      background-color: transparent
    }`

The background becomes transparent.

Hope this helpsl

You need the latest release of the windrose-card.  There was a long standing bug preventing card_mod to work, which I today finally fixed. It needed a small code change, but it took me a lot of time to find out what to change.
