### ISSUE TITLE
Unable to find file?

### ISSUE THREAD

**Issue by KruseLuds** [aukedejong/lovelace-windrose-card#14]
Please note I have Home Assistant Supervised, and there is no specific config/www directory, but I do have:

homeassistant/www

so, note these are the results from the command line (the wget line is cut and pasted from the instructions so that I can make sure there were no spelling mistakes:

`
pi@kruse-pi:/usr/share/hassio/homeassistant/www$
pi@kruse-pi:/usr/share/hassio/homeassistant/www$ sudo wget https://github.com/aukedejong/lovelace-windrose-card/releases/download/latest/windrose-card.js
--2023-04-24 08:34:35--  https://github.com/aukedejong/lovelace-windrose-card/releases/download/latest/windrose-card.js
Resolving github.com (github.com)... 140.82.114.4
Connecting to github.com (github.com)|140.82.114.4|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2023-04-24 08:34:35 ERROR 404: Not Found.
pi@kruse-pi:/usr/share/hassio/homeassistant/www
pi@kruse-pi:/usr/share/hassio/homeassistant/www$ wget https://github.com/aukedejong/lovelace-windrose-card/releases/download/latest/windrose-card.js
--2023-04-24 08:35:07--  https://github.com/aukedejong/lovelace-windrose-card/releases/download/latest/windrose-card.js
Resolving github.com (github.com)... 140.82.114.4
Connecting to github.com (github.com)|140.82.114.4|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2023-04-24 08:35:08 ERROR 404: Not Found.

`

**Comment by aukedejong** [comment]
I don't think I tested the manual install instruction. I can check this evening.

HACS is the preferred way to install and manage custom cards. Is it an option for you to install HACS?
Card version update are easily done from the HA user interface.

Also, this card will be available in HACS by default in hopefully the next HACS version.

**Comment by aukedejong** [comment]
I found the mistake:
This should be the command to download the JS:

`wget https://github.com/aukedejong/lovelace-windrose-card/releases/latest/download/windrose-card.js`

I'll correct the readme.  Thanks for asking.
