### ISSUE TITLE
Correction to instructions (hope this helps)

### ISSUE THREAD

**Issue by KruseLuds** [aukedejong/lovelace-windrose-card#15]
Maybe this is copied from something a long time ago, but you canot add resource settings any more the way it is described. When I get into the raw configuration editor* and try to save the resources it does not allow me to add it. I was forced to add the resources by using this:

1. Open any lovelace view
2. Select from the three dot menu - "edit dashboard"
3. The three dot menu is then replaced with another one, select the new three-dot menu (and do not select raw configuration editor*, it will tell you when you try to save it with the resource section, that for adding resources you have to use the three-dot menu choice "Manage Resources" instead). Select "Manage Resources"
4a. Click "Add Resource", 
4b. enter this for url: 
`/local/wndrose-card/js?v=0.0.1`
4c. click the check box for "Javascript Module" and 
4d. click the word "Create" in the corner to add the entry.

**Comment by aukedejong** [comment]
I change the readme. Added your part to it.
I'm in YAML mode, so I still need to use the configuration.yml for this.

Thanks.
