### ISSUE TITLE
russian translation

### ISSUE THREAD

**Issue by Psytoshgen** [aukedejong/lovelace-windrose-card#16]
Can you give some strings to translate on russian? I will do.
and one thing, cant understand, mps - meter per second or mile?

**Comment by aukedejong** [comment]
mps is meter per second.
You're right, that's not very clear in the docs.  I'll change that.

That card doesn't use any internationalisation.  I think it will only be needed for the unit names right?

**Comment by Psytoshgen** [comment]
Well maybe so.
Anyway 
m/s - м/с
kph - км/ч
mph - миль/ч
bft - По Ботфорту
knots - узлов

This card i think more interesting in wind bearing than compas card =) ty for your work!

**Comment by aukedejong** [comment]
The latest version has the option to set colors of different parts of the windrose.

About the translations. I made an option to set the output units name. There you can put any text you like. This way the card can support any language.
It not ready yet, will be in the next 24 hours.

**Comment by aukedejong** [comment]
Released version 0.11.0

The output speed unit name can now be changed to support different languages.
