### ISSUE TITLE
Feature Request: Set Color of Rose Lines, Percentage Displays

### ISSUE THREAD

**Issue by CharlesCage** [aukedejong/lovelace-windrose-card#17]
First off, thank you so much for your work on this. It's just freakin' awesome. :)

I'd be cool if we had the ability to set custom colors for (separately):

- he rose lines/wind speed box
- NESW letters
- Wind Speed words
- Rose percentages
- Speed bar percentages

And if you aren't interested or don't have time, thanks anyway. What a great card.

**Comment by aukedejong** [comment]
It's at the top of the backlog.
Thanks.

**Comment by aukedejong** [comment]
Released v0.10.0

The color of these parts can now be configured:
    roseLines
    roseDirectionLetters
    rosePercentages
    barBorder
    barUnitName
    barName
    barUnitValues
    barPercentages

If you find any bugs, please let me know.
