### ISSUE TITLE
Only gettin NaN as values

### ISSUE THREAD

**Issue by jayjayvm** [aukedejong/lovelace-windrose-card#18]
Hi Auke,

I use Buienradar as base for the information, and that is working here for years already so in meteo info I see the windspeed and direction. But when I put them into the set-up from the card only NaN gets displayed no values are getting used?

**Comment by aukedejong** [comment]
Hi Jayjay,
You also posted on the forum. Lets continue here.
Or there any errors printed in the browser console?

**Comment by aukedejong** [comment]
I believe you got it working with help of the community.

**Comment by jayjayvm** [comment]
Yes Auke it is largely solved, I did not get the windrose working with the letter option, but the azimuth option does work, pretty well, so yes pleased, thank you all!
