### ISSUE TITLE
Card background mismatch with custom HA theme

### ISSUE THREAD

**Issue by lorenzobaldoni** [aukedejong/lovelace-windrose-card#2]
The background of the card doesn't match the colour of the other cards when using custom home assistant themes. The issue doesn't appear when using the default theme.
This is what it looks like in my case with google theme for example. 

![image](https://user-images.githubusercontent.com/69859080/214946318-88b56e21-1d8d-4fbc-bfda-ed4d3cf906e9.png)

**Comment by aukedejong** [comment]
Can you share the link to the theme you're using?

Ik tried [https://github.com/JuanMTech/google_dark_theme](https://github.com/JuanMTech/google_dark_theme), but could not reproduce the problem yet.

**Comment by aukedejong** [comment]
Release v0.2.1 with a possible fix.

**Comment by lorenzobaldoni** [comment]
The problem seems to persist even after updating to v0.2.1. The theme I'm using is this:
https://github.com/JuanMTech/google-theme

**Comment by lorenzobaldoni** [comment]
I also noticed that in the card preview it looks good.

![image](https://user-images.githubusercontent.com/69859080/215140289-4daea952-37eb-412f-8ed3-6a26ef2ad97f.png)

**Comment by aukedejong** [comment]
Tried it with the same theme you're using. Still can't reproduce it.

Did you already try to clear browser cache and refresh the dashboard?

**Comment by aukedejong** [comment]
Glad I could help.
