### ISSUE TITLE
Error after update 6/9/2023

### ISSUE THREAD

**Issue by paulearley** [aukedejong/lovelace-windrose-card#24]
This wonderful weather tool created an error after the latest update. The rose does not appear and the error is: WindRoseCard: No wind_direction_entity.entity configured. I am using a Tempest weather sensor. I have the entity sensor.weatherflow_wind_direction in my entity list and can display it using the native Home Assistant card.

**Comment by aukedejong** [comment]
Did you update the configuration? 
Changes need to be made.

**Comment by aukedejong** [comment]
Added info about the breaking changes at the top of de readme. 
Thanks.

**Comment by olivierouellet** [comment]
Hi Paul. You can [close this issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/closing-an-issue) if everything is ok on your side.
