### ISSUE TITLE
Blank card. Error: Could not convert direction unknown to degrees

### ISSUE THREAD

**Issue by olivierouellet** [aukedejong/lovelace-windrose-card#26]
When restarting Home Assistant, my sensors have an `unknown` state for a short period of time.
It seems like it's not a major problem for the speed entity, but it is for the direction entity (which is in letters for me), so there's no rendering of the card until time passes and I no longer have any `unknown` state in the timeframe specified with `hours_to_show` .

Would it be possible to ignore any value that have an `unknown` state? I don't restart often so not a big deal for me, but it might prevent strange issues down the road. Also, should it include `unavailable` and `None` states?

This is what I get in Chrome console:
<img width="798" alt="unknown" src="https://github.com/aukedejong/lovelace-windrose-card/assets/85790609/79d2ce5f-ae3c-40e2-8f59-44668054a0af">

**Comment by olivierouellet** [comment]
I got another error with `unavailable` instead of `unknown` . Again no rendering of the card for a while and then suddenly worked again after a few hours.
<img width="806" alt="Unavailable" src="https://github.com/aukedejong/lovelace-windrose-card/assets/85790609/d56afb6a-6af4-4254-ac62-cd6c74f85cb5">
Lovelace Windrose card 1.0.0 - Home Assistant 2023.6.1 - Supervisor 2023.06.1 - Operating System 10.2 - User Interface: 20230608.0 - Chrome 114.0.5735.106

**Comment by aukedejong** [comment]
Release version 1.0.1
Now ignoring wind directions that are not a number.

Thanks Olivier for helping others, gives me more time to fix things.

**Comment by aukedejong** [comment]
Release version 1.0.2

- Unit of measurement kn now recognized as knots.
- Not recognized directions now ignored.
- Not recognized speeds now ignored.
