### ISSUE TITLE
[RQST] hours_to_show automatic since midnight

### ISSUE THREAD

**Issue by GH2user** [aukedejong/lovelace-windrose-card#31]
Hi Auke,
Very nice card you created.
Would it be possible to have an option to use the data since midnight (00:00) in order to see the wind information for today?
Thanks.

**Comment by aukedejong** [comment]
That would be a nice option. I'll try to add this in the next feature release.

I'll keep updated in this issue.

**Comment by aukedejong** [comment]
Released version 1.2.0
It contains your feature request. See readme on how to configure.

Thanks for your request.
