### ISSUE TITLE
[Feature request] card using a background image

### ISSUE THREAD

**Issue by carryonrewardless** [aukedejong/lovelace-windrose-card#32]
This great card could be enhanced by enabling the selection of an image as a background to the windrose display. An example would be to have the windrose overlay an image of the house (plan view) at the location.
Cheers

**Comment by aukedejong** [comment]
A made the windrose transparent before, for someone who added to card to an picture elements card, if I remember correctly.
Maybe you can use that card. 

And with card_mod you can set CSS styles. A background-image css?

I don't have much time to work on new features, the coming weeks.

**Comment by ildar170975** [comment]
Surely may be added by card-mod (background-image); need to use a png image with a transparent bottom part (where a scale is displayed).

**Comment by olivierouellet** [comment]
The other issue was #12 . The proposed solution was to add this to the card configuration (although I've never used it myself) :
```
card_mod:
  style: |
    ha-card {
      background-color: transparent
    }
```

**Comment by carryonrewardless** [comment]
I have this in my card config but get no background image.  The path to the image file is valid.
```
card_mod:
  style: |
    ha-card {
      background-color: transparent;
      background: url('/local/images/DSC_0718.png');
    }
```

Tried also with background-image and also without the semi-colons.

**Comment by carryonrewardless** [comment]
Ok my bad. I had created a /local folder instead of putting it into /www.
Now its working fine.
Had to select rose lines colours as transparency and opacity parameters were not doing anything.
![image](https://github.com/aukedejong/lovelace-windrose-card/assets/7085477/9ba7bdf8-61aa-42fc-89c1-475f8700c92a)

**Comment by ildar170975** [comment]
> need to use a png image with a transparent bottom part (where a scale is displayed).

as it was said earlier.

**Comment by aukedejong** [comment]
The windbar is also drawn on a canvas, so the text can't be styled with CSS.
I'm working on an option to hide the windbar.
You can also use Ildars option and make the background higher, so the windbar is drawn under the floor plan.

**Comment by ildar170975** [comment]
Just some thoughts:
can we use TWO canvas elements placed one after one inside an upper container?
![image](https://github.com/aukedejong/lovelace-windrose-card/assets/71872483/78e7eb87-3735-4f53-9088-37de1ba17412)
Then hiding the scale may be achieved by not showing the 2nd canvas.
Also, the background image may be selected to the "rose" canvas then:
![image](https://github.com/aukedejong/lovelace-windrose-card/assets/71872483/5641c327-e5fb-4db7-a4d1-1ce177ed87f8)

**Comment by aukedejong** [comment]
That's not the plan. Maybe in the future. It's a bigger change then the one I'm working on now.

Currently the new hide option doesn't draw the windbar.

Also good for performance for lower end devices.

**Comment by carryonrewardless** [comment]
I created a new image file with 100% transparency at the bottom using LibreOffice Draw.  The bottom section was by inserting an additional rectangle area.  The main image area was set to 10% transparency but this did not seem to do much. Here is the result.
![image](https://github.com/aukedejong/lovelace-windrose-card/assets/7085477/cfd48435-65dc-4d6c-8ef6-f8afb91577f7)

**Comment by ildar170975** [comment]
My remark is not about the implementation - - it is about using an image in general.
I think the best way is showing a map:

![image](https://github.com/aukedejong/lovelace-windrose-card/assets/71872483/b7bd3094-2012-4742-81eb-114ab8aa7b9e)

```
card_mod:
  style: |
    canvas {
      background-image: url('/local/images/test/country-plot.png') !important;
      background-size: 100% 100%;
    }
```

**Comment by aukedejong** [comment]
I think this one can be closed. It's possible with card_mod to use a background image.
