### ISSUE TITLE
wind rose legend

### ISSUE THREAD

**Issue by satya0210** [aukedejong/lovelace-windrose-card#36]
the  plots  have 
![plot1](https://github.com/aukedejong/lovelace-windrose-card/assets/100069922/e0f75107-9ed7-43f5-93ff-31a82dcdbf9a)
![plot2](https://github.com/aukedejong/lovelace-windrose-card/assets/100069922/4824ae70-8275-4b12-8b80-31ddb557227e)
different legend

i want fix the range of the lengend

my code is here

from windrose import WindroseAxes
from matplotlib import pyplot as plt
import matplotlib.cm as cm
from numpy.random import random
from numpy import arange
import pandas as pd
MON=pd.read_csv(r'data.csv')
ws = MON["Ws"].values
wd = MON["Wd"].values
ax = WindroseAxes.from_ax()
ax.set_ylim(0,50)
ax.bar(wd, ws, normed=True, opening=0.8, edgecolor='white')
ax.set_title('plot2')
ax.set_legend()

**Comment by aukedejong** [comment]
Question for someone else's windrose library.

**Comment by olivierouellet** [comment]
Hi @satya0210. Go to this repository for your question : [python-windrose](https://github.com/python-windrose/windrose) .
