### ISSUE TITLE
[Feature request] Hide bar option

### ISSUE THREAD

**Issue by L0bit0** [aukedejong/lovelace-windrose-card#37]
Can we hide the bar, to just show the rose?

thanks!

**Comment by aukedejong** [comment]
Not possible at the moment.  Should be easy to add.
Maybe I can find some time the coming week.

**Comment by ildar170975** [comment]
https://github.com/aukedejong/lovelace-windrose-card/issues/32#issuecomment-1627388023

**Comment by aukedejong** [comment]
Released version 1.3.0
New option to hide the windspeed bar(s): hide_windspeed_bar

Please close the issue if this is what you requested.  Thanks.

**Comment by L0bit0** [comment]
It worked, great!

Thanks so much!

**Comment by L0bit0** [comment]
functionality added. thanks!
