### ISSUE TITLE
Numbers in and next to the bar

### ISSUE THREAD

**Issue by rdwdm** [aukedejong/lovelace-windrose-card#40]
Hello,
Is there a way to disply the numbers in and next to the bar (lower part) better?
![ps](https://github.com/aukedejong/lovelace-windrose-card/assets/77530559/380fa13c-2e09-4a9d-820a-9ac7574c9470)

**Comment by aukedejong** [comment]
Hello. You could set the windspeed_bar_full option to false.
Other option is to use other speedranges. Maybe set the Beaufort option to false or configure complete custom speedranges.

If you have an other idea on how to solve this, please let me know.

**Comment by rdwdm** [comment]
Hello,
windspeed_bar_ful to false is an option but I'm wondering why aren't the colored squares not equal in size.
If all are equal (to font size) it would looks better.
![IMG_5784](https://github.com/aukedejong/lovelace-windrose-card/assets/77530559/1a87fefa-f277-4387-89d9-33186ce16cb0)

Another option would be the possibility to turn off the percentages, they are already more or less in the windrose.

**Comment by aukedejong** [comment]
The sizes are relative to the speed ranges. Beaufort is not a linear 'unit'.
Maybe I can create an option that turns off the relative block sizes and distribute it equal. More like an legend.
I'll have a look and let you know.

**Comment by aukedejong** [comment]
Released version 1.4.0

The feature you requested.

**Comment by rdwdm** [comment]
Hi Auke,

I updated the card and added " render_relative_scale: false" to the config and it's working.
IMHO, It's looking much better this way.

Many thanks for all your effort for this great card.

BR Ron
