### ISSUE TITLE
Card not displaying

### ISSUE THREAD

**Issue by zagi988** [aukedejong/lovelace-windrose-card#42]
Any idea why is the card simply not displaying? Neither in edit mode nor in view mode.

Card:

`

type: custom:windrose-card
title: Wind rose
data_period:
  hours_to_show: 24
max_width: 400
refresh_interval: 60
windspeed_bar_location: bottom
windspeed_bar_full: true
wind_direction_entity:
  entity: sensor.gw1100a_wind_direction
  direction_unit: degrees
  use_statistics: true
  direction_compensation: 0
windspeed_entities:
  - entity: sensor.gw1100a_wind_speed
    speed_unit: auto
    use_statistics: false
speed_range_beaufort: true
windrose_draw_north_offset: 0
cardinal_direction_letters: NESW
matching_strategy: direction-first
center_calm_percentage: true

`

How it shows:
![image](https://github.com/aukedejong/lovelace-windrose-card/assets/24916202/bbd9eee1-e725-4450-b987-b69805d6d3e4)

Javascript is latest, wind_direction has a unit °, speed has a unit km/h.

**Comment by aukedejong** [comment]
Can you any errors in the console? Please share them here.
F12 in the browser.

**Comment by zagi988** [comment]
Turns out wind_direction wasn't in statistics so "use_statistics: true" couldn't be used. Would be good if it showed the error in frontend tho.
