### ISSUE TITLE
[Feature request] Format text color based on windspeed color

### ISSUE THREAD

**Issue by autumnwalker** [aukedejong/lovelace-windrose-card#47]
Hello!

Is it possible to format the text color based on the windspeed color? The default "light" color scheme uses a dark blue background and black text for the initial windspeed / center of rose - it is difficult to read.

If you change rose_percentages to white then they become illegable outside of the center. If you change bar_percentages then they become illegable on the lighter wind speed colors.

**Comment by aukedejong** [comment]
Can you share a screencapture here?

So you would like the text color to change depending on the background color.
Do you have an idea on how to do that, without using al lot of different colors?

**Comment by aukedejong** [comment]
I'll think about this.
Don't have much time to spare. Maybe  I can fix something during the Christmas holidays.

Thanks for your input.

**Comment by autumnwalker** [comment]
Got some more wind yesterday - another screenshot to illustrate the white text on colored background.
![IMG_0023](https://github.com/aukedejong/lovelace-windrose-card/assets/11489678/879c6950-183a-41e9-b5ba-35cbbb347e77)

**Comment by autumnwalker** [comment]
Thank you!
