### ISSUE TITLE
Blank screen and error in browser console

### ISSUE THREAD

**Issue by jezinke** [aukedejong/lovelace-windrose-card#53]
I just installed the windrose-card 1.4 in HA 2023.1.3 and have this behavier: 

![grafik](https://github.com/aukedejong/lovelace-windrose-card/assets/87004993/da2aba6b-e551-4bde-bc36-785d84ba4f3c)

The card shows blank and the entity is definitely correct as I can add it to any other lovelace card with success.

![grafik](https://github.com/aukedejong/lovelace-windrose-card/assets/87004993/8f7c4c4a-6c50-42e0-b919-9141a9499624)

 Any help appreciated.

**Comment by ildar170975** [comment]
Post a minimal code reproducing this error.

**Comment by jezinke** [comment]
This is my config
type: custom:windrose-card
title: Wind direction
data_period:
  hours_to_show: 1
max_width: 400
refresh_interval: 300
windspeed_bar_location: bottom
windspeed_bar_full: true
wind_direction_entity:
  entity: sensor.gw2000b_wind_direction
  direction_unit: degrees
  use_statistics: false
  direction_compensation: 0
windspeed_entities:
  - entity: sensor.gw2000b_wind_speed
    name: windspeed
    speed_unit: mph
    use_statistics: false
output_speed_unit: mph
input_speed_unit: mph
speed_range_beaufort: false
windrose_draw_north_offset: 0
cardinal_direction_letters: NESW
matching_strategy: direction-first
center_calm_percentage: true

this is the resource manager

![grafik](https://github.com/aukedejong/lovelace-windrose-card/assets/87004993/c137506f-4677-44f3-833a-aa22e3b7845d)

this is what the card looks like

![grafik](https://github.com/aukedejong/lovelace-windrose-card/assets/87004993/0b47c07f-7f90-41b0-8a47-bab97f1fa3dd)


No log entries regarding this card, just installed via hacs, added to card to a dashboard and entered the config.
Thank you for taking care.

**Comment by ildar170975** [comment]
The code you posted is unformatted. You could have noticed it yourself. It will be really hard (may be even impossible) for people to analyse it.
Compare your post with other issues here.

**Comment by jezinke** [comment]
This is the code which shows up after including the card. I only inserted the entities for direction and speed and the speed unit. nothing else. Here a screen print of the code. It comes in 2 parts, split at line 15. What would be a MINIMAL code?

![grafik](https://github.com/aukedejong/lovelace-windrose-card/assets/87004993/318b052d-0d00-4df0-bf9d-19c05b0b3e0c)
![grafik](https://github.com/aukedejong/lovelace-windrose-card/assets/87004993/78d5b626-0e4f-41e8-9ddf-c214bad599c8)

**Comment by ildar170975** [comment]
> Here a screen print of the code.

People may want to reproduce your issue in their setups.
Screenshot cannot be copy/pasted as yaml.

> I only inserted the entities for direction and speed and the speed unit. nothing else.

I see, then let's consider this as a minimal.

**Comment by jezinke** [comment]
solved the problem. entities had not been in the recorder include. Might be good to note in the instruction that entity date is taken from history. Many with a raspberry don't record all entities automatically to save sd card lifetime.
Thank you.
