### ISSUE TITLE
Card not working in companion app (iOS)

### ISSUE THREAD

**Issue by ruteclrp** [aukedejong/lovelace-windrose-card#55]
Getting: custom element doesn't exist: windrose-card

Works fine in browser on phone and pc

**Comment by ruteclrp** [comment]
Well😳. Now it works in the IOS app. Have no clue as to why it has started working. At first, the color scheme for fonts and background was out of tune with the normal/dark mode. 

This morning, the color scheme works just right????

We can thus close this issue.

**Comment by aukedejong** [comment]
Maybe it has something to do with caching in the app.

In the iOS app there is an option to reset the frontend cache.

Settings > Companion app > Debugging > Reset frontend cache
