### ISSUE TITLE
No longer displaying after switching to Beaufort scale supported by HA 2024.4 

### ISSUE THREAD

**Issue by ChaoticOrb** [aukedejong/lovelace-windrose-card#58]
I changed over the units for wind speed and gusts as they are now supported in HA and the windrose stopped displaying. It doesn't error just won't display. If I change back, it works again. Could this be supported?

**Comment by etmnidj1** [comment]
Same problem here, card is not displaying anything. Bft would be great! Really like the card; on top of my weatherstation page!

**Comment by aukedejong** [comment]
Hi
I'll try to find the time to fix this.
Hopefully it's a quick fix.

**Comment by aukedejong** [comment]
Update:
Just had a quick look at the code and did some tests.
I'm not sure it's is a HA bug, but when you change the unit to Beaufort, historical measurements are not changed. The windrose uses history data to create the rose.

So, if the unit switch is within the windrose data period, the windrose will discard measurements or maybe interpret wrong.

Later this week more.

**Comment by ChaoticOrb** [comment]
Ah good point, it just flips the units over and keeps recording against the same entity. In a couple of other cards it tries to display both B and km/h together which makes a mess. I’ll see if it clears up once the historical data being used is all using Beaufort. Thanks for looking!

**Comment by aukedejong** [comment]
Release v1.5.0.
Should be fixed now.
If you have any problems, please let me know.

**Comment by ChaoticOrb** [comment]
That works perfectly! Thank you
