### ISSUE TITLE
Bug: Beaufort as input wind speed unit 

### ISSUE THREAD

**Issue by FvanEgmond** [aukedejong/lovelace-windrose-card#59]
Latest Release (31) of this card is not able to handle wind speed entities with have Beaufort as unit of measurement. 
Since Home Assistant 2024.4 this is configurable for wind speed entities.
Note: speed_unit: auto does not work either. 
Therefore, kind request to add Beaufort as possible (recognizable) speed_unit for windspeed_entities. 
Thanks in advance, and cheers for the great work done so far!

**Comment by aukedejong** [comment]
Yesterday I released v1.5.0 with support for Beaufort.
I think 31 is the previous one, because there are 32 releases now.

Can you try the newer version?

**Comment by FvanEgmond** [comment]
Ha! I typed this in yesterday but didn't press submit. Now it's already fixed. Newer version works perfectly, with speed_unit: auto. Thanks for the very fast fix! Cheers.
