### ISSUE TITLE
[Feature request] Allow different speed ranges for wind speed entities

### ISSUE THREAD

**Issue by prenetic** [aukedejong/lovelace-windrose-card#60]
Requesting the capability to individually configure speed ranges for different wind sources. The current implementation is applied to every wind source.

This would be useful when presenting adjusted wind speeds correlated to comfort levels (e.g., Lawson Comfort Criteria) as a secondary wind source, which have a much lower range compared to absolute wind speed measurements.

Mockup:
<img width="367" alt="image" src="https://github.com/aukedejong/lovelace-windrose-card/assets/11982895/d31243e7-dd89-43f5-802b-45d6e415c277">

**Comment by Aaroneisele55** [comment]
I would also love to have different ranges for my two Wind Speed entities (Average/Gust) so I can analyse them better...

**Comment by aukedejong** [comment]
Feature added in version 1.12.0.
