### ISSUE TITLE
[Bug] Three or more windspeed scales not properly rendered

### ISSUE THREAD

**Issue by prenetic** [aukedejong/lovelace-windrose-card#61]
When displaying three or more windspeed scales, rendering issues are present.

1. The third wind speed source is partially cut off, and as a result is missing the text underneath the windspeed scale.
2. The fourth wind speed source and beyond are cut off entirely.

For users trying to display wind speed breakdowns from multiple wind speed sources, this limits the frontend integration to 2 wind speed sources.

Visualization:
<img width="288" alt="image" src="https://github.com/aukedejong/lovelace-windrose-card/assets/11982895/4a47dbcc-215a-4e4a-9881-bb82b09b720c">

**Comment by aukedejong** [comment]
Just released a new version with vector graphics.
I tested with 4 speed sources and it render correctly.

This should be fixed, please let me know.

**Comment by prenetic** [comment]
Looks like it's working -- thanks!
![image](https://github.com/user-attachments/assets/fe632d4a-e248-4fc7-bc45-a553a80f3a39)

Just want to point out a new issue though, if the card isn't the last item in a column under the new style of dashboard, other entities will overlap. Since there's no visual option to adjust the layout (height/width) the only workaround I've found is to nest the card inside a grid or stack which takes care of the overlap.

![image](https://github.com/user-attachments/assets/c6abed61-59a7-4920-b7f5-c9f15353d1fe)

**Comment by aukedejong** [comment]
Did you update to the latest 1.6.2?
It has a fix for the sections view type dashboard.

**Comment by prenetic** [comment]
Apparently not, apologies! Didn't realize there was another update. Everything is working, thanks again.
