### ISSUE TITLE
Calculates the wind direction only on changes

### ISSUE THREAD

**Issue by seg-on** [aukedejong/lovelace-windrose-card#64]
It calculates the wind direction only if the wind direction changes.
So if there was a change of wind two times in the average day and N blew 23h and NW 1h in the graph it will be shown as N 50% and NW 50%.
The wind direction is stored in the form of letters.

Last 24h Direction:
![image](https://github.com/aukedejong/lovelace-windrose-card/assets/19683952/282306f2-7459-4dc7-be07-c6b72edcd5a6)

Windorse card:
![image](https://github.com/aukedejong/lovelace-windrose-card/assets/19683952/5a251247-7473-4bad-a9ae-42394501385e)

It is possible to fix it?

**Comment by aukedejong** [comment]
I understand the problem.  Maybe switching the matching-strategy from direction-frist (default) to speed-first.
It also depends on how much speed updates your sensor reports.

**Comment by seg-on** [comment]
Hi @aukedejong,
I'm scraping data from the website and it only stores changes. The database only stores data when the direction or speed is changed. Changing the match strategy won't solve the problem because the wind speed is stored in the same way.

**Comment by aukedejong** [comment]
Thanks for explaining.
To support this, we need an new matching strategy.  
A strategy that determines for every times step the last known values.  The time step size and how far back in time can be configured. Now I think about it, maybe this strategy wil create the better graphs.

I hope I can find time to work in this.

**Comment by seg-on** [comment]
Hi
Thank you. I changed the matching strategy but now it does not give me any result.
![image](https://github.com/user-attachments/assets/67cb80cb-3b8e-4d87-8b6f-7bc29aea48c4)

I may have done something wrong in my configuration:
`type: custom:windrose-card
title: 24h
data_period:
  hours_to_show: 24
max_width: 600
refresh_interval: 300
windspeed_bar_location: bottom
windspeed_bar_full: false
wind_direction_entity:
  entity: sensor.shmu_pn_smer
  direction_unit: letters
  direction_letters: SVJZX
  use_statistics: false
windspeed_entities:
  - entity: sensor.shmu_pn_vietor
    name: rýchlosť
    speed_unit: mps
    use_statistics: true
output_speed_unit: mps
input_speed_unit: mps
speed_range_beaufort: false
cardinal_direction_letters: SVJZ
matching_strategy: time-frame
center_calm_percentage: false
speed_range_max: 20
speed_range_step: 1`

**Comment by aukedejong** [comment]
Justed tested it with an 'letters' sensor.   Normally I use the 'degrees' sensor.   There seams to be a bug related to letter sensors...
Sorry, I will fix this.

**Comment by aukedejong** [comment]
Fixed in version 1.11.0
Can you try again?

**Comment by seg-on** [comment]
Great. Looks like it works. Thank you :)
![image](https://github.com/user-attachments/assets/02191d4e-64e4-45da-b74c-fb3b07547f88)
![image](https://github.com/user-attachments/assets/2b2c3bd4-815c-49b1-bd53-f70c54d06fd0)
