### ISSUE TITLE
[Feature Request] Possibility to change direction of direction arrow to point inward

### ISSUE THREAD

**Issue by fkolacek** [aukedejong/lovelace-windrose-card#71]
First of all, thank you for developing this addon, it is really useful! 

I was wondering if it would be possible to introduce a configuration option (e.g. `current_direction_arrow: true`) allowing to switch the direction of the direction arrow to face inward? My weather station is providing wind direction in I guess "non-standard" way, showing the direction the wind is flowing from and not to and I suppose there will be other folks experiencing the same.

**Comment by aukedejong** [comment]
Hi,
Some else also asked to change the direction of the arrow.
Currently the arrow is to pointing the direction where the wind is coming from.
I will change this.
My plan is to change the arrow direction, pointing to the center of the rose.

**Comment by aukedejong** [comment]
Release in 1.8.0.
