### ISSUE TITLE
Current wind direction arrow is not persistent.

### ISSUE THREAD

**Issue by johndvz800** [aukedejong/lovelace-windrose-card#72]
Hi,
For me the current wind direction arrow is not persistent. After clearing the cache the arrow will show up for 20-30 seconds and then disappear unitil the cache is cleared again.

**Comment by aukedejong** [comment]
Hi,
Currently I working on a new features, which also required refactoring of the current wind code.
Hopefully this fixed the issue, but I will investigate.

I'm planning to release today.

Thanks for letting me know.

**Comment by baloo2** [comment]
After 1.8.0 update I get error "Current converted wind direction is undefined". Current value of wind direction is VRB (variable wind direction showed no arrow in previous versions).

**Comment by JulianDHall** [comment]
Hello thank my arrow is now persistent!
