### ISSUE TITLE
Current converted wind direction is undefined

### ISSUE THREAD

**Issue by baloo2** [aukedejong/lovelace-windrose-card#73]
After 1.8.0 update I get error "Current converted wind direction is undefined". Current value of wind direction entity is VRB. I am sure variable wind direction showed no arrow in previous version...

**Comment by aukedejong** [comment]
I'm working on the fix right know.  But how should this be fixed?  VRB is not a direction.  
What would you like?   Hiding the arrow?  I'm not sure if that is a good idea.
Maybe ignoring VBR and use the previous direction.

**Comment by baloo2** [comment]
Well, personally I am ok with no arrow if wind is variable. Or you can use some other pictogram (other than arrow) in case of variable wind. I don't think direction 0 in case of VRB is a good idea either...

**Comment by aukedejong** [comment]
I agree, but it's the quick fix I did in version 1.8.1, so the card doesn't crash.
Tomorrow I have more time to work in this.

When the arrow is hidden, people may think it's a bug.    Some other way, red circle in the middle maybe.   Or turning the arrow in a circle, on the location of the last measure direction.

**Comment by baloo2** [comment]
Red circle in the middle is great idea.

**Comment by aukedejong** [comment]
Fixed in version 1.8.2
Implemented the red circle.
