### ISSUE TITLE
Direction arrow being left behind

### ISSUE THREAD

**Issue by lloyda** [aukedejong/lovelace-windrose-card#79]
Occasionally I'm seeing the direction arrow not being erased when I change dashboards.  Currently using v1.8.2, but have seen on earlier versions

![image](https://github.com/user-attachments/assets/98fe413a-6199-49f8-bded-b9f9bfb18a88)

**Comment by aukedejong** [comment]
I have it too, don't know why it is happening yet.
Will be fixed in the next version. (hopefully :-)
