### ISSUE TITLE
v0.7.0 doesn't install correctly in HACS and the release doesn't include windrose-card.js 

### ISSUE THREAD

**Issue by natekspencer** [aukedejong/lovelace-windrose-card#8]
Tried to update to the latest version and after a reload I saw a message saying custom element windrose-card does not exist. Upon further investigation, it looks like the windrose-card.js isn't getting compiled for v0.7.0.

**Comment by aukedejong** [comment]
My bad. Forgot to add the js.  Should be fixed now.
