### ISSUE TITLE
[Feature Request] More flexible cardinal point labels

### ISSUE THREAD

**Issue by Homie-O-Stasis** [aukedejong/lovelace-windrose-card#82]
Can cardinal_direction_letters be changed to display more than one letter per compass point? Perhaps the input text can be delimited or made into an array, like cardinal_direction_letters: “N,E,S,W”?

I would like to be able to customise the names of the points to use the card to represent the direction of the solar wind, measured in two directions with a positive or negative sign.

For example cardinal_direction_letters: “Bz+,By+,Bz-,By-”, so there’s still four labels but they have more than one character.

**Comment by aukedejong** [comment]
Thanks for adding it here.
I find it very interesting that you're using this card to show solar winds.

**Comment by aukedejong** [comment]
Added this feature in version 1.11.0
As you described, comma seperated.

**Comment by Homie-O-Stasis** [comment]
Thanks very much! This is a very welcome feature for my use case.
