### ISSUE TITLE
show_arrow does not work

### ISSUE THREAD

**Issue by Ace0510** [aukedejong/lovelace-windrose-card#83]
Since the last update wind arrow direction does not display. Am I doing something wrong?

type: custom:windrose-card
title: Wind direction (5 min)
data_period:
  hours_to_show: 4
refresh_interval: 300
windspeed_bar_location: right
windspeed_bar_full: true
current_direction: true
show_arrow: true
arrow_size: 60
center_circle_size: 30
wind_direction_entity:
  entity: sensor._wind_dir
  direction_unit: degrees
  use_statistics: false
  direction_compensation: 0
windspeed_entities:
  - entity: sensor.wind_speed
    name: Wind Speed
    speed_unit: auto
    use_statistics: false
  - entity: sensor.wind_gust
    name: Wind Gust
    speed_unit: auto
    use_statistics: false
output_speed_unit: kph
speed_range_max: 50
speed_range_step: 5
speed_range_beaufort: false
windrose_draw_north_offset: 0
cardinal_direction_letters: NESW
matching_strategy: speed-first
center_calm_percentage: false
colors:
  rose_lines: rgb(50,250,100)
  rose_direction_letters: white
  rose_center_percentage: white
  rose_percentages: white
  rose_current_direction_arrow: red
  bar_border: hsl(300, 100%, 60%)
  bar_unit_name: black
  bar_name: white
  bar_unit_values: white
  bar_percentages: null

<img width="251" alt="Screenshot 2024-10-10 110532" src="https://github.com/user-attachments/assets/6c0082e3-a0a3-47e9-9109-71bd74505d0e">

**Comment by aukedejong** [comment]
Since version 1.10.0? 

`Can you add the config in a code block?  So can easily copy paste and check things.`

**Comment by Ace0510** [comment]
Sorry about that. Here is the code. V1.10.0. Before it was working fine.
Thanks,

` type: custom:windrose-card
title: Wind direction (5 min)
data_period:
  hours_to_show: 4
refresh_interval: 300
windspeed_bar_location: right
windspeed_bar_full: true
current_direction: true
show_arrow: true
arrow_size: 60
center_circle_size: 30
wind_direction_entity:
  entity: sensor.el_encanto_wind_dir
  direction_unit: degrees
  use_statistics: false
  direction_compensation: 0
windspeed_entities:
  - entity: sensor.el_encanto_wind_speed
    name: Wind Speed
    speed_unit: auto
    use_statistics: false
  - entity: sensor.el_encanto_wind_gust
    name: Wind Gust
    speed_unit: auto
    use_statistics: false
output_speed_unit: kph
speed_range_max: 50
speed_range_step: 5
speed_range_beaufort: false
windrose_draw_north_offset: 0
cardinal_direction_letters: NESW
matching_strategy: speed-first
center_calm_percentage: false
colors:
  rose_lines: rgb(50,250,100)
  rose_direction_letters: white
  rose_center_percentage: white
  rose_percentages: white
  rose_current_direction_arrow: red
  bar_border: hsl(300, 100%, 60%)
  bar_unit_name: black
  bar_name: white
  bar_unit_values: white
  bar_percentages: null

`

**Comment by aukedejong** [comment]
If you add this, it should work.

```
current_direction:
  current_direction: true
  show_arrow: true
```

**Comment by Ace0510** [comment]
Thanks you!!!Alberto On Oct 11, 2024, at 3:15 PM, Auke de Jong ***@***.***> wrote:﻿
If you add this, it should work.
current_direction:
  current_direction: true
  show_arrow: true
