### ISSUE TITLE
Cannot read properties of undefined (reading 'time_interval')

### ISSUE THREAD

**Issue by muhkuh666** [aukedejong/lovelace-windrose-card#85]
I get the error message "Cannot read properties of undefined (reading 'time_interval')"  

`type: custom:windrose-card
title: Windrose Tag
hours_to_show: 24
max_width: 400
refresh_interval: 300
windspeed_bar_location: right
windspeed_bar_full: true
wind_direction_entity:
  entity: sensor.easyweatherv1_6_5_wind_direction
windspeed_entities:
  - entity: sensor.easyweatherv1_6_5_wind_speed
    name: Windgeschwindigkeit
  - entity: sensor.easyweatherv1_6_5_wind_gust
    name: Windböen
wind_direction_unit: degrees
input_speed_unit: kph
output_speed_unit: kph
direction_compensation: 0
windrose_draw_north_offset: 0
cardinal_direction_letters: NESW
matching_strategy: direction-first
direction_speed_time_diff: 1
`

Idea why? Anyone?

**Comment by mash727** [comment]
Yip that works perfectly, many thanks
