### ISSUE TITLE
Issue when windspeed is zero for a number of hours

### ISSUE THREAD

**Issue by gedger** [aukedejong/lovelace-windrose-card#86]
We're in a period of zero wind so no wind speed data has been logged for 6 hours as Home Assistant only stores data if there is a change. 

The Windrose card doesn't handle this situation, see picture.

Setup to use the last 3 hours of data.

![IMG_0285](https://github.com/user-attachments/assets/0c21b5e4-21c4-4fb7-8be4-67d44e147a84)

![IMG_0286](https://github.com/user-attachments/assets/cf0bdc29-87d2-4225-a2b2-dee6cfadfc03)

**Comment by aukedejong** [comment]
Hi, thanks for reporting this.
Did a quick fix. Now showing default percantages, instead of NaN values.
