### ISSUE TITLE
Card sometimes extending below the dashboard, lone direction arrow

### ISSUE THREAD

**Issue by AndLindemann** [aukedejong/lovelace-windrose-card#87]
I‘m still seeing an issue similar to #79 where the card extends towards the bottom of the dashboard and a lone direction arrow is visible there.
Especially happens on the iOS companion app with mobile dashboards for me.

Maybe this is related to pages where the card is not visible or only visible in popups, like in conjunction with the „bubble card“.

This is with the current 1.11.1 version of the card:

![5878099E-385E-40CE-8297-C16569E9BF89](https://github.com/user-attachments/assets/d60f2929-2ac1-453a-bce8-f7d2b03fba78)

**Comment by aukedejong** [comment]
Thanks for your detailed report.
Looks like the some issue. 

I can't reproduce it on iOS yet.  Maybe I need to try something with the bubble card.

Before the issue only presents it self when editing the card.  Did you do that in the iOS companion app?

You are sure the companion app is using the latest version of the card?

**Comment by AndLindemann** [comment]
I have reset the fronted cache in the app several times. So I think that’s all I can do to get it to load the most recent version.
I have not edited the card in the app, so I can rule that out. I do all my dashboards directly in yaml.

I think there is a relationship to bubble card somehow, as I can only reproduce the issue so far, when I access a dashboard using bubble card, where Windrose is configured in a bubble card popup. 
After that however the issue also presents itself in non-bubble-card dashboards. Looks like once it has broken, it breaks on other dashboards as well, until I reload the app.

**Comment by AndLindemann** [comment]
I can reproduce this on Firefox/Windows also with a bubble-card dashboard, so not only related to iOS/companion app. There's the assumed svg tag being rendered below the dashboard.

![grafik](https://github.com/user-attachments/assets/fa4a089c-b5bb-40fe-b6dd-00271d81624e)

**Comment by aukedejong** [comment]
Hi,
When an error occurs in the windrose card, the SVG library I use just adds an svg element to the dom.
Before I fixed this by catching errors and clean up.

Can you see any errors in the browser console related to the windrose card?

**Comment by AndLindemann** [comment]
I can see it initializes with the "Windrose Card Version 1.6.0" message - I have 1.6.2 installed, but I checked and it looks like it always outputs 1.6.0 currently.

The only other message from windrose card I see is

`WR WARN Matching results entity sensor.weatherly_wind_gust, 1 not matched of total 842 direction measurements`

The card seems to work fine though (apart from the described issue 😊).

**Comment by AndLindemann** [comment]
I think this is fixed with the new SVG library.

**Comment by aukedejong** [comment]
I think so too. Thanks.

FYI, just released a new version. There was a safari related issue.
