### ISSUE TITLE
Time interval is null?

### ISSUE THREAD

**Issue by knuckleheadsmiff** [aukedejong/lovelace-windrose-card#88]
Updated today oct/12 cleared chance, refreshed page and see new error:

![IMG_0930](https://github.com/user-attachments/assets/e7ccc639-700d-45a7-b474-c581eff3cbfd)

**Comment by knuckleheadsmiff** [comment]
Fixed number of data period number of hours to show in yaml and it’s fixed but since the doc says time_interval defaults to 60 of not defined I still think this is a bug.

**Comment by aukedejong** [comment]
Try this:

data_period:
  hours_to_show: 400

**Comment by knuckleheadsmiff** [comment]
I’ll close it, fixing yaml does work (as said earlier.)
