### ISSUE TITLE
Cannot read properties of undefined error

### ISSUE THREAD

**Issue by carryonrewardless** [aukedejong/lovelace-windrose-card#89]
Getting error:Cannot read properties of undefined (reading 'time_interval')
I am on  v1.11.1 and HA is version 2024.9.1.
this has been working for me up until v1.10.1.
How do I trouble-shoot this?

**Comment by aukedejong** [comment]
Try this:

data_period:
  hours_to_show: 400

**Comment by carryonrewardless** [comment]
Thanks. Yes I saw this on the other post but it has not changed anything for me.

**Comment by knuckleheadsmiff** [comment]
It’s clear that the something changed and when the yaml is not correct the code does not default like it used to.  The particular value it is complaining about should be defaulted if not defined according to the doc. I closed my bug because I fixed it by fixing the yaml. 

It doses work if you add/change (noticed the indenting.

`
data_period:
  hours_to_show: 4
`

**Comment by knuckleheadsmiff** [comment]
i’m thinking at one time “number of hours” was not under the “data period” section but can’t be sure but now has to be defined there. So at one point a breaking change was introduced.

**Comment by knuckleheadsmiff** [comment]
> Try this:
> 
> data_period: hours_to_show: 400

I think you mean 4 not 400? 400 is a lot of hours!

**Comment by aukedejong** [comment]
I do tests with 400 hours. 😄 

The data_period object was introduced in version 1.2.0.

Release notes:  [https://github.com/aukedejong/lovelace-windrose-card/releases/tag/v1.2.0](https://github.com/aukedejong/lovelace-windrose-card/releases/tag/v1.2.0)

The previous location of the hours_to_show property is deprecated.

I added a new matching strategy.  That broke the fall back to the deprecated option.

Thank you for looking a bit further and deeper.

I will release a new version with fix.

**Comment by aukedejong** [comment]
Released version 1.11.2
