### ISSUE TITLE
Corner entity decimal places

### ISSUE THREAD

**Issue by leedare** [aukedejong/lovelace-windrose-card#92]
The corner entity for the wind speed isn't honouring the decimal places so I get this.

![image](https://github.com/user-attachments/assets/59e04317-e1e5-4b2a-9fe4-f80c444005e8)

**Comment by JanK9** [comment]
For me, the wrong decimal places are displayed, for example, 2.1944444444444 or 2.921111111111.
But I also get e.g. the value 4.5 in the correct format.
I have the basic settings for the entity to one decimal place.
Thanks in advance for the correction.

**Comment by aukedejong** [comment]
Fixes in version 1.11.3.
Can you check?

**Comment by leedare** [comment]
I get this? Anyone else? Its cropped with a title.

![image](https://github.com/user-attachments/assets/9f0afdec-8786-4684-b83e-5a461c24eab2)

**Comment by aukedejong** [comment]
I don't have this, but could be a bug. The card is using an other draw library.
Can you share your card configuration?

**Comment by aukedejong** [comment]
Just checked again. I have this too on my phone.
Need to investigate.

**Comment by aukedejong** [comment]
Released version 1.11.4.
Was a safari related issue. Should be fixed now, can you check?

**Comment by leedare** [comment]
Looks good here thanks.

![image](https://github.com/user-attachments/assets/dad378d3-bb75-4f8c-a675-72e772026931)
