### ISSUE TITLE
South Cardinal only Partially Visible

### ISSUE THREAD

**Issue by JulianDHall** [aukedejong/lovelace-windrose-card#97]
The South cardinal point is only partially visible when the wind bar is removed.  I can replicate this in Masonry View, Sections and Sections with Horizontal Stack.  It would appear the margin needs to be larger when the wind bar is not being used.  Edit 1: This view is in Masonry

![image](https://github.com/user-attachments/assets/fbd7e43e-c972-495f-b603-5d3fcbfda752)

**Comment by aukedejong** [comment]
HI Julian, thanks for reporting this issue.
The card is getting to complex to check every possible configuration option.

I found the problem in the code, but can't test it right now. I'm not at home and the VPN server is broken.
Fix wil be coming in a few days.

**Comment by aukedejong** [comment]
Should be fixed in version 1.11.6.  Can you confirm this?

**Comment by JulianDHall** [comment]
Yes.  Looks perfect!  Thank you for fantastic card
