### ISSUE TITLE
Corner entity text case

### ISSUE THREAD

**Issue by leedare** [aukedejong/lovelace-windrose-card#98]
I was looking at putting the text wind direction in the corner entity but it is appearing as lower case? I have left the unit on just as a demo.

![image](https://github.com/user-attachments/assets/5a1f54e8-4bf7-444e-8e65-8806ca1e6948)

I don't think it is my sensor, as on an entity card it shows as.
![image](https://github.com/user-attachments/assets/0132d5fa-7151-4715-b220-03bb186fef28)

And in my history.
![image](https://github.com/user-attachments/assets/c86db1d1-beb1-4c8b-ab3f-b542ee5b365b)

**Comment by aukedejong** [comment]
First, thanks for the perfect issue report with screencaps.

I also have an entity with letters, showing upper case letters everywhere in HA.
Also in the windrose card.

I can't explain what you're seeing.

Did a code search on case manipulation. The only time it's doing something like this, is when you want letters converted to degrees and than it's converted to uppercase not lowercase.  And it's only for calculation purposes, not for displaying.

Then again, I can add a configuration option, to manipulate case if needed.

A quick fix could be a template sensor, something like this: 

```
{{ states('sensor.wind_direction') | upper }}
```

Didn't test this and I don't have much experience with template sensors.

**Comment by leedare** [comment]
Thanks for confirming. It looks like HA is converting it in the entity card and history as if I look in the dev tools > states or templates it is shown as lower case. So yes, I'll fix it with a template sensor.

**Comment by aukedejong** [comment]
Maybe this should be a change in the integration providing this entity.

I'll close this one, thanks.
